//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloMobiiliMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talot
    {
        public int TaloId { get; set; }
        public string TaloNimi { get; set; }
        public Nullable<int> TaloTavoiteLampotila { get; set; }
        public Nullable<int> TaloNykyLampotila { get; set; }
        public Nullable<bool> LampoOff { get; set; }
        public Nullable<bool> LampoOn { get; set; }
    }
}
